### ISSUE TITLE
横スクロール可能表示

### ISSUE THREAD

**Issue by YuseiIto** [Shiga-pref-org/covid19#14]
## 改善詳細 / Details of Improvement
- 横スクロール可能な表に、その旨を表示したい

## 期待する見せ方・挙動 / Expected behavior
-感染者属性の表が 横スクロール可能な場合のみ、「横にスクロールできます」と表示したい

## 動作環境・ブラウザ / Environment
- Every environment

**Comment by t-okushima** [comment]
対応しました。
ご確認ください。
