### ISSUE TITLE
「お子様をお持ちの皆様へ」のJSON整備

### ISSUE THREAD

**Issue by YuseiIto** [Shiga-pref-org/covid19#17]
「お子様をお持ちの皆様へ」ページは、pages/parent.vue によりページ構造を定義し、pages/parent.i18n.jsonで多言語対応する構造になっています。

parent.vue内の表示される文字列が、全て $t('str')　となるようにした上で、そのカッコ内のそれぞれの文字列をkeyとしてjson側に加えてください。つまり、日本語側は jsonのkey==　vueの括弧内　ということになるように、確認してください。日本語版に合わせて他の言語は同じkeyを使うので、日本語版にのみ変更を適用していただければそれで結構です。

この作業が終了次第、このページの翻訳が開始されます。

**Comment by OldBigBuddha** [comment]
🙋‍♀️

**Comment by OldBigBuddha** [comment]
と思ったけどそもそもすでに完成している…？
https://github.com/Shiga-pref-org/covid19/blob/development/pages/parent.i18n.json

**Comment by YuseiIto** [comment]
えっ...!? 申し訳ないです🙇‍♂️
