### ISSUE TITLE
SideNavigationコンポーネント のJSON整備

### ISSUE THREAD

**Issue by YuseiIto** [Shiga-pref-org/covid19#19]
SideNavigationは、全てのページで読み込まれている大切なコンポーネント です。
components/SideNavigation.vue　ファイル中の表示される文字列が、全て `$t('str')`　となるようにした上で、そのカッコ内のそれぞれの文字列をkeyとしてjson側に加えてください。つまり、日本語側は jsonのkey==　vueの括弧内　ということになるように、確認してください。日本語版に合わせて他の言語は同じkeyを使うので、日本語版にのみ変更を適用していただければそれで結構です。

**Comment by OldBigBuddha** [comment]
日本語の部分は問題ないですが他の言語のキーが修正されていないのでそこだけ修正しておきます。

**Comment by YuseiIto** [comment]
問題なかったですか? 申し訳ない..もう一度きちんと確認します。他の言語のkeyは後から自動で直すので大丈夫です。
