### ISSUE TITLE
i18n用JSONファイルのテストを実装する

### ISSUE THREAD

**Issue by YuseiIto** [Shiga-pref-org/covid19#22]
多言語対応のJSONがページ中の全てのkeyを網羅しているかのテストを実装して、未翻訳のところを検出したいです。
おそらくvueファイルを解析して`$t()`の中身が全てkeyとして書かれているかを確かめれば実装できると思います。

なお、テストを実装したいというだけで、どこに実装したいかは決めかねています。
別で実行するscriptsとして実装するか、github actionsでci的に運用するかなど、アイデアのある方はこちらに書いていただけると助かります。

**Comment by YuseiIto** [comment]
(主観ですが、実装自体はそこそこ楽しいと思うのでよろしくお願いします!)

**Comment by rioil** [comment]
Pythonで少し書いてみました
コードが汚いかもしれないのでコメントを結構書いておきました
https://gist.github.com/rioil/d44a475710fa21c8d16f1d55b754e8e2

**Comment by YuseiIto** [comment]
ありがとうございます!　今手元環境で試しました!!
期待していた以上の物ができていて驚いています。

せっかくなら良い場所にこのscriptを配置したいので、`/tool`の中に入れたいのですが、その作業をお願いしてもいいですか? 
`/tool`の中から実行して、`/pages`と`/components`を見に行くような感じです。`auto-i18n`　ディレクトリは `/pages`,`/components`のそれぞれに作っていただければokです。完了したらPRで飛ばしてください。

あと少し、お手数をおかけしますが、よろしくお願いします!
