### ISSUE TITLE
参考元の表示

### ISSUE THREAD

**Issue by OldBigBuddha** [Shiga-pref-org/covid19#24]
## 改善詳細 / Details of Improvement
- index で表示しているデータの出典を明記したほうが良いのでは

## 期待する見せ方・挙動 / Expected behavior
![image](https://user-images.githubusercontent.com/13755428/77662562-5e509f00-6fbf-11ea-9ef1-f8e981cd1285.png)

ref: 京都版コロナウイルス対策サイト

## 動作環境・ブラウザ / Environment
- All browser

**Comment by YuseiIto** [comment]
ご指摘ありがとうございます。
県公式で運営しているため、情報ソースが自明であること、オープンデータカタログサイトにはないため別でダウンロードできる場所がないことより、意図して削除されています。一旦closeします。また何かあったらおっしゃってください。
