### ISSUE TITLE
FAQページがあると良いのでは

### ISSUE THREAD

**Issue by YuseiIto** [Shiga-pref-org/covid19#28]
## 改善詳細 / Details of Improvement
- よく相談される内容をまとめて、FAQ的なページを作れると良いのではないか。
(参考: これまでに、Code for San Fransiscoがそれに向けて動き出している。)

## 期待する見せ方・挙動 / Expected behavior
- サイドメニーにFAQのリンクを置く
- 開くとパネル状に質問が並んでいる
- 各パネルのhoverやclickでそのパネルが下方向に展開し、質問に対する答えを表示する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by youichirou** [comment]
これはサイトについてのFAQではなくて、「滋賀県におけるCOVID19対策行政、およびCOVID19そのものについてのFAQ」ということですよね。

**Comment by YuseiIto** [comment]
そうです!

**Comment by Shiga-pref** [comment]
個人や事業主に対する問い合わせF&Qやフローの掲載を検討しています。フローチャートの概要をまとめていますので、それが出来次第issuesにあげたいと思います。
