### ISSUE TITLE
「お子様をお持ちの皆様へ」ページの内容の改善

### ISSUE THREAD

**Issue by YuseiIto** [Shiga-pref-org/covid19#29]
## 改善詳細 / Details of Improvement
- 現在の「お子様をお持ちの皆様へ」ページは、「3.その他」のわずかな文章以外は「お子様をお持ち」でなくても必要になる情報である。

-　このページのキャプションを適切に変更し、別で特に育児や学校に関連するトピックを構成したページを設けてはどうか

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by Shiga-pref** [comment]
・お子様をお持ちの皆様へ→県民の皆様へ　が適切かと思います。
・ページ内の「臨時休校中の」の文言を削除する
・3.その他を「県教育委員会等の対応（学校等）」として一旦リンクを貼ってはいかがでしょう（PDFばっかりであまり見せられるページではないですが・・・）
　→https://www.pref.shiga.lg.jp/edu/school/hokentaiiku/anzenkyusyoku/hoken/310418.html

**Comment by YuseiIto** [comment]
ここで「一旦...」と妥協して急ぐ必要はないので、できれば学校向けの情報を除いて、保護者や児童生徒に向けた情報に特に絞って出せる方が良いのではと考えています。保守の方法を含めて課題はあるので、議論せねばなりませんが...

**Comment by Shiga-pref** [comment]
こちらは「教育委員会からのお知らせ」として、https://www.pref.shiga.lg.jp/edu/school/hokentaiiku/anzenkyusyoku/hoken/310418.html
にリンクを貼る方向で進めようと思います。
