### ISSUE TITLE
イベントや施設の状況を提供する

### ISSUE THREAD

**Issue by YuseiIto** [Shiga-pref-org/covid19#30]
## 改善詳細 / Details of Improvement
- 現在、「滋賀県の施設の状況」「滋賀県主催等　中止または延期するイベント等」などのページは県のウェブサイトへのリンクとなっているが、どれもPDFであまりにも不便。UXを改善したい。

## 期待する見せ方・挙動 / Expected behavior
- 当サイト内で、表や地図の形式でわかりやすく掲載するのが良いのではないか
- その場合、県の担当の方が非ITでも更新可能なよう、GoogleスプレッドシートまたはCSVの形式でデータを取り入れられると良い。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by Shiga-pref** [comment]
非ITでも簡単に更新（データ取り込み等で）できるのであれば、そっちの方がいいですね~

**Comment by youichirou** [comment]
ちなみに、参考までに勝手に作った私のマップですが、
http://testsystems.sakura.ne.jp/coronamap/

![image](https://user-images.githubusercontent.com/3391965/77726289-ede76380-703a-11ea-9a4b-1a757efa2930.png)

このGoogle スプレッドシート
https://docs.google.com/spreadsheets/d/1hXUSHrZF9TSc4zpBERLHy8rIQk1Jqn0dcktyZoDkPpc/edit?usp=sharing

をJSONで読めるように「ウェブに公開」しまして、
それをサイト上のVueから読んで表示する形になっています。

スプレッドシートを書き換えるだけで反映できますので、更新作業負荷は低いと思われます。
※ちなみに緯度経度はいちいち一個ずつジオコーディングサイトとかGoogleマップを使って調べています(笑)

**Comment by YuseiIto** [comment]
良いですね。地図のライセンスってどうなってましたか?　
もしかするとgmapではなくosmあたりにした方が安全かもなという気がするのですが。

**Comment by youichirou** [comment]
少なくともこのサイトは自分がGoogleにクレジットカードを登録して表示していて、アクセス数が一定を超えたら課金されます。
Open Street Mapが使えるならそっちの方がよさそうですね。

**Comment by YuseiIto** [comment]
なるほど。確かにyouichirouさんのサイトでは問題がないですね。こちらではOSMの方が良さそう。OSMをvueで使ってみたことはあるので、実装するならその方針でいきましょう。
(県公式にこれを実装して良いということがはっきりすれば)

**Comment by Shiga-pref** [comment]
①OSMを実装してよいか？
②データを担当課が随時更新してくれるか
この２点を確認させていただきます。

**Comment by youichirou** [comment]
今のところ滋賀県は東京みたいに感染者がどんどん増えてるわけでもないし、増えてきたとしても「感染者情報の推移を見れるサイト」ってだけではどうも掲載情報として寂しいというか、ICTの活用としてそれだけでいいのだろうか、という疑問がありまして。
感染者情報以外の行政の情報のビジュアライズが充実した方が県民のニーズに資するように思うんですよね。

施設やイベント以外ににも載せるといい情報があるかどうかみなさんに募ってみたい気もします。
(すでに以前の会合で話し合われてたらアレですけども)

**Comment by YuseiIto** [comment]
そうですね。全く同意です。
補足しますが、OSMに関しては、これまでにVueで使ってPinをつけて..とやったことがあるので、実装することになればそのコンポーネント を流用可能と思います😆

**Comment by youichirou** [comment]
> ①OSMを実装してよいか？
> ②データを担当課が随時更新してくれるか
> この２点を確認させていただきます。

について、
①のOSMについてはまあ、ライセンス的にも費用的にも問題は無いと思いますが、
②についてはいろいろとハードルがありそうです。

うちらの負荷で言えば、
↑大
①我々メンバーの誰かが https://www.pref.shiga.lg.jp/ippan/kenkouiryouhukushi/yakuzi/310183.html を随時確認して、我々でPDFの内容をJSONやスプレッドシートに転記して、それをCOVID19Shigaの表示データとする
②県職員が ↑ のPDFを作るついでに、PDFの元になるExcelかなんかをうちらに提供してもらい、我々がJSON等に加工、それを表示データとする
③県職員が ↑ のPDFを作るついでに、JSONやCSV等のデータを作ってもらいどこかにアップロード、それを表示データとする
④県職員が ↑ のPDFを作るついでに、我々が用意したGoogleスプレッドシートに県職員が入力してもらい、それを表示データとする
↓小

というあたりで、おそらくお忙しいであろう県職員さんにどこまでお願いできるのか、というのはありますね。といいつつもうちらもヒマではないので①は避けたい…。
あと、そもそも県庁のイントラネットからGoogleスプレッドシートにアクセスは可能なのか、とか、担当する県職員さんのスキルとか…。

**Comment by Shiga-pref** [comment]
お世話になっています。
お見込みのとおり、
・県職員のマンパワー的に厳しい
・県職員のITスキルが部署によって全く異なる
とった状況ですので、こちらのissueについては対応が難しいところです。
提案いただいたところですが、申し訳ありません。
