### ISSUE TITLE
事業者/個人に対する制度ページの作成

### ISSUE THREAD

**Issue by t-okushima** [Shiga-pref-org/covid19#33]
## 改善詳細 / Details of Improvement
- 以下滋賀県での制度や国で実施している制度ページの作成
  - [中小企業者向け制度融資のご案内（新型コロナウイルス関連）](https://www.pref.shiga.lg.jp/ippan/shigotosangyou/kigyou/309618.html)
    - HTMLとPDFで記載されており見ずらい。

## 期待する見せ方・挙動 / Expected behavior
- 当サイト内でわかりやすく掲載する
- 当サイト内での掲載が難しい場合、わかりやすく誘導する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by YuseiIto** [comment]
表記の改善を含む追加ですので、検討が必要です。しばらくお待ちください。

**Comment by YuseiIto** [comment]
ちなみに、当該のページはかなり情報量の多いものだと思うのですが、それを当サイト内で `わかりやすく` 表示することについて何かアイデアがあればお伺いしたいです。(そこまではまだわからないということでもOKです)

**Comment by youichirou** [comment]
以前Slackで、このフローの滋賀県版は作られないのか、と言う発言をさせてもらったことがありますが、
https://stopcovid19.metro.tokyo.lg.jp/flow

こういう感じのビジュアライズ→詳細はPDFで、という感じでなんとかなる複雑さであればよいのですが。

**Comment by youichirou** [comment]
ただ、イベント情報のほうもですが、一度載せるだけなら簡単ですが、改訂が行われたときに情報が陳腐化しますので、担当課から更新のたびに連絡がもらえるような枠組みを作らないと、県からの情報発信の妨げになってしまうことも気をつけなければならないと思います。

**Comment by YuseiIto** [comment]
そう思います。特に企業に関連するところは誤った表現が許されないセンシティブな情報なので、アップデートがあるたびに毎回更新せねばならず、それは開発サイドとしても少々荷が重いように思います。

- 貼っていただいたページへのリンク
- 特に重要な情報の要約

をまとめた企業向けの最新情報を、Vueですでに実装されている既存コンポーネント の組み合わせで作る方がうまく運用していけるのではないかと考えています。

**Comment by t-okushima** [comment]
特に画面を考えての発言ではないです。
すみません。

事業者など制度を利用する側が、国や県の情報を探す労力を減らせたらと思い記載しました。

**Comment by YuseiIto** [comment]
いえいえ。このウェブサイトが目的を実現する上で、大切な指摘だと思います。ありがとうございます。せっかくの指摘なので、うまく実現できるよう検討していきたいですね!

**Comment by t-okushima** [comment]
東京都の[企業の皆様・はたらく皆様へ](https://stopcovid19.metro.tokyo.lg.jp/worker)のような感じになりますかね。

[生活困窮者自立支援制度](
https://www.pref.shiga.lg.jp/ippan/kenkouiryouhukushi/chiiki/14822.html)なども考える必要がありますが。

**Comment by fujisawa-e** [comment]
この対策サイトが県民にとってワンストップでわかりやすいページであることが一番ですね！
なので、さまざまなコンテンツを集約できればと思うのですが、公式サイトの責任部門である広報課とも意識を合わせる必要を感じます。
というのも、
https://www.pref.shiga.lg.jp/ippan/kenkouiryouhukushi/yakuzi/309252.html
これが、広報課が考える現時点の滋賀県の対策ページだと思うのですが、ここに今回作成した対策サイトのリンクがありません。滋賀県公式を謳っているのにです。
東京都はもちろん、神奈川、大阪などはすべてバナーなどで誘導されるようになっていますので、これはとても不自然に感じます。
対策サイトで独自のコンテンツを発信すると言うより、県の公式サイトにあるさまざまな情報にワンストップでたどり着いていただけるような設計をまず考えていければと思います。
その過程で、東京都のフローのようなものがあればわかりやすいようなら、それは当チームでは制作が難しいので外注するなどしていければいいですね。

**Comment by Shiga-pref** [comment]
コロナで広報課がパンク気味で対応が厳しかったですが、ようやく滋賀県ホームページの掲載にこぎつけそうです。もう少しだけお待ちください。
事業者向けについては
https://www.pref.shiga.lg.jp/ippan/kenkouiryouhukushi/yakuzi/309252.html#a04
にリンクを貼ろうかと思っています。内容更新を後追いするのは難しいので、これが限界かな、と思います。

**Comment by YuseiIto** [comment]
となると、これは公式として公開する上で難しい、という理解で構いませんか?　であればcloseしたいと思います。

**Comment by YuseiIto** [comment]
https://www.pref.shiga.lg.jp/ippan/kenkouiryouhukushi/yakuzi/309252.html#a04　へのリンクが貼られたのでcloseします。
