### ISSUE TITLE
感染予防について

### ISSUE THREAD

**Issue by t-okushima** [Shiga-pref-org/covid19#38]
## 改善詳細 / Details of Improvement
- 以下記事の「石けんの効果とウイルスに打ち勝つ仕組み」の様に、各感染予防の方法が、どう効果的なのかを伝える事で意識を向上できるのではないか
  - [life hacker - なぜ、石鹸はウイルスに効果的なのか？](https://www.lifehacker.jp/2020/03/how-soap-works.html)
- 咳エチケットを求めているが、正しい方法について記載がない
- 「手洗い、咳エチケット等」の「等」には何が含まれているのか

## 期待する見せ方・挙動 / Expected behavior
- サイト内で、各感染予防の方法とその効果を明記する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by Shiga-pref** [comment]
外部サイトへのリンクは厚労省など公的なサイトが良いと思います。https://stopcovid19.pref.shiga.jp/parentで【参考】感染症予防のための正しい手洗い方法（PDF）は掲載しているところですが、ほかに厚労省で良さそうなページがあれば掲載したいと思います。

**Comment by YuseiIto** [comment]
このissueはずっとpendingがついたままになっています。
どう対応するのか、県として方針を示していただきたいです。

**Comment by Shiga-pref** [comment]
感染予防については既に手洗いについてpdfを掲載しておりますので、クローズしたいと思います。
