### ISSUE TITLE
滋賀県 新型コロナウイルス感染症 対策サイトへの導線の確保

### ISSUE THREAD

**Issue by t-okushima** [Shiga-pref-org/covid19#55]
## 改善詳細 / Details of Improvement
- 滋賀県 新型コロナウイルス感染症 対策サイトへの導線が確保されていない。

## 期待する見せ方・挙動 / Expected behavior
- 滋賀県HPのトップ及び、滋賀県の状況トップページからの導線を作成する。
- SNSでの発信

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

## もととなるコメント
- https://github.com/Shiga-pref-org/covid19/issues/33#issuecomment-605929303

**Comment by Shiga-pref** [comment]
現状について
滋賀県ホームページへの掲載は現在申請中です。
LINE公式アカウント「滋賀県-新型コロナ対策パーソナルサポート」（友だち登録者数：54,483 R2.4.9現在）のタイムラインおよび最新情報メニューにリンクを掲載しています。

**Comment by YuseiIto** [comment]
@t-okushima  ありがとうございます!　そうですよね、県公式サイトとして運用する以上重要と思います。

@Shiga-pref 
これ、どういう意味でpendingなんですか....やりとりだけをみる限りcloseして良さそうですが...

**Comment by Shiga-pref** [comment]
@YuseiIto 
現状は滋賀県ホームページにリンクが貼れていないので、完了次第closeしようと思っていました。確かにpendingではないですね。

**Comment by YuseiIto** [comment]
@Shiga-pref ではそれでお願いします。紛らわしいので一度ラベルはとります。

**Comment by YuseiIto** [comment]
@Shiga-pref これ、リンク掲載されているように見受けられますが、これ以上に何かされる見込みがありますか?なければcloseしてください。
<img width="878" alt="スクリーンショット 2020-04-19 16 31 53" src="https://user-images.githubusercontent.com/23429049/79682198-4933fc80-825b-11ea-9eb2-708c9e23b494.png">

**Comment by Shiga-pref** [comment]
広報課へは上部のスライド画像に配置するように依頼しましたが、「一旦はこの状態にする、後からスライド画像に移す」と回答がありました。このままの状態で放置される可能性はあります。少し不本意ではありますが動線は確保されたということでクローズしたいと思います。
