### ISSUE TITLE
病床数の公開

### ISSUE THREAD

**Issue by t-okushima** [Shiga-pref-org/covid19#56]
## 改善詳細 / Details of Improvement
- 確保している病床数の公開
  - 東京/大阪などは記者会見の場で確保した病床数を公表している。
  - 滋賀県がどのような行動をとっているか示すことができ、すこしでも安心感を与えることができるのではないか。

## 期待する見せ方・挙動 / Expected behavior
- 重症/軽症患者様に用意している病床数、及び利用状況を公開する。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by Shiga-pref** [comment]
病床数については引き続き調整中です。

**Comment by YuseiIto** [comment]
この表示ですが、毎日新聞社様の担当者よりぜひ表示すると良いと提案をいただいています。積極的に検討を進めていただくようお願いいたします。

**Comment by Shiga-pref** [comment]
病床数掲載についてですが、正式な情報が降りてこないため掲載が難しいです。一旦クローズさせて頂き、情報提供できる状態になりましたら再度issuesにあげたいと思います。
