### ISSUE TITLE
年代毎の感染者数の表示

### ISSUE THREAD

**Issue by t-okushima** [Shiga-pref-org/covid19#59]
## 改善詳細 / Details of Improvement
- 年代毎の感染者数を表示する。
  - どの世代でも感染し死に至る病であるが、意識があまり高くない人を見受ける。この情報から少しでも意識を変えることができないか。

## 期待する見せ方・挙動 / Expected behavior
- 年代毎の感染者数をグラフ表示

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by Shiga-pref** [comment]
年代別に表示することで、逆に若い世代なら大丈夫等、誤った判断をされる恐れがあります。
全年代に注意していただくのであれば、年代別の表示はしないほうがベターと考えます。
